In [4]:
import numpy as np
import os

In [5]:
data_dir = '/storage/yw18581/data/'
data_folder = os.path.join(data_dir, 'train_validation_test')

In [6]:
unet_dir = os.path.join(data_dir, "trained_models",
                        "UNet_training_generator_1500epochs")

In [9]:
def cut_X(arr, reshape = None):
    x_cut = arr[:,960:1300,600:]
    if reshape:
        if len(x_cut.shape)>3:
            x_cut = x_cut[...,0]
            x_cut_out = x_cut.reshape(x_cut.shape[0],x_cut.shape[1]*x_cut.shape[2])
    else:
        x_cut_out = x_cut
    return x_cut_out

def reshape_RF(arr):
    arr_RF = arr.reshape((arr.shape[0], arr.shape[1]*arr.shape[2]))
    return arr_RF

In [10]:
def cut_reshape(arr):
    arr_cut = cut_X(arr)
    arr_RF = reshape_RF(arr_cut)
    return arr_RF

In [11]:
def import_splitted_gt(pos):
    Xy = np.load(os.path.join(data_folder,"Xy_"+pos+"_clean.npz"))
    X = Xy["y"]
    y = Xy["dist"]
    X_RF = cut_reshape(X)
    indices = np.load(os.path.join(data_folder,"RF_train_test_indices_80_20_"+pos+"_clean.npz"))
    training_indices = indices["train"]
    test_indices = indices["test"]
    X_RF_train = X_RF[training_indices]
    y_train = y[training_indices]
    X_RF_test = X_RF[test_indices]
    y_test = y[test_indices]
    return X_RF_train, y_train, X_RF_test, y_test

In [13]:
def import_splitted_UNet(pos):
    Xy = np.load(os.path.join(unet_dir,"Xy_"+pos+"_clean_predicted_UNet.npz"))
    X = Xy["y"]
    y = Xy["dist"]
    X_RF = cut_reshape(X)
    indices = np.load(os.path.join(data_folder,"RF_train_test_indices_80_20_"+pos+"_clean.npz"))
    training_indices = indices["train"]
    test_indices = indices["test"]
    X_RF_train = X_RF[training_indices]
    y_train = y[training_indices]
    X_RF_test = X_RF[test_indices]
    y_test = y[test_indices]
    return X_RF_train, y_train, X_RF_test, y_test

In [14]:
X_30mm_cl_UNet_RF_train, y_30mm_cl_UNet_train, X_30mm_cl_UNet_RF_test, y_30mm_cl_UNet_test  = import_splitted_UNet("30mm")

In [15]:
y_30mm_cl_UNet_train

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30])

In [16]:
y_30mm_cl_UNet_test

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30])

In [17]:
np.unique(X_30mm_cl_UNet_RF_test[0])

array([  0, 255], dtype=uint8)

In [22]:
len(X_30mm_cl_UNet_RF_test)

37

In [24]:
for i in range(37):
    print(np.unique(X_30mm_cl_UNet_RF_test[i]))

[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]
[  0 255]


In [25]:
model = np.load(os.path.join(data_dir, "RF30_trained_model_clean_data.npz"))["rf"][-1]

In [26]:
type(model)

sklearn.tree.tree.DecisionTreeRegressor

In [27]:
model.feature_importances_

array([0., 0., 0., ..., 0., 0., 0.])

In [28]:
np.nonzero(model.feature_importances_)

(array([119202, 129357, 130101, 134448, 135728, 142905, 142953, 144954,
        151710, 159469, 159647, 169308, 171545, 173347, 174923, 175736]),)

In [29]:
feature_indices = np.nonzero(model.feature_importances_)

In [31]:
X_30mm_cl_UNet_RF_test[0][feature_indices]

array([255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255], dtype=uint8)

In [33]:
model.tree_.decision_path

<function Tree.decision_path>

In [34]:
model.predict(X_30mm_cl_UNet_RF_train)

array([35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 30., 35.,
       35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35.,
       30., 35., 30., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35.,
       35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 30.,
       35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35.,
       35., 30., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35.,
       35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 30., 35.,
       35., 35., 30., 35., 35., 35., 35., 30., 35., 35., 35., 35., 35.,
       35., 35., 35., 35., 35., 35., 35., 30., 35., 35., 35., 35., 35.,
       35., 30., 35., 35., 35., 35., 35., 35., 30., 35., 35., 35., 35.,
       35., 35., 35., 30., 35., 35., 35., 35., 35., 35., 35., 35., 35.,
       35.])

In [35]:
model.predict(X_30mm_cl_UNet_RF_test)

array([35., 35., 35., 35., 35., 35., 35., 35., 35., 30., 35., 35., 35.,
       35., 35., 35., 35., 35., 35., 30., 35., 35., 35., 35., 35., 35.,
       30., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35.])

---

In [37]:
import pickle

loaded_model = pickle.load(open(os.path.join(data_dir,"RF30_8_trained_model_clean_data.npz"), 'rb'))

In [38]:
type(loaded_model)

sklearn.ensemble.forest.RandomForestRegressor

In [39]:
loaded_model.predict(X_30mm_cl_UNet_RF_test)

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  30 out of  30 | elapsed:    0.0s finished


array([35.        , 33.66666667, 35.        , 35.        , 35.        ,
       35.        , 35.        , 33.5       , 35.        , 30.66666667,
       35.        , 35.        , 34.83333333, 35.        , 35.        ,
       35.        , 35.        , 33.33333333, 35.        , 30.        ,
       35.        , 35.        , 33.        , 33.83333333, 35.        ,
       35.        , 32.66666667, 35.        , 32.5       , 35.        ,
       35.        , 33.83333333, 35.        , 35.        , 35.        ,
       33.5       , 35.        ])

In [43]:
np.nonzero(loaded_model.feature_importances_)[0].shape

(395,)

In [44]:
X_20mm_cl_UNet_RF  = import_splitted_UNet("20mm")

In [45]:
Xunet_train, yunet_train, Xunet_test, yunet_test = X_20mm_cl_UNet_RF

In [46]:
yunet_train

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20])

In [47]:
yunet_test

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20])

In [48]:
loaded_model.predict(Xunet_train)

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  30 out of  30 | elapsed:    0.0s finished


array([20.83333333, 20.16666667, 20.        , 20.66666667, 20.66666667,
       20.66666667, 20.5       , 20.83333333, 21.        , 20.66666667,
       21.        , 20.66666667, 21.        , 20.66666667, 20.83333333,
       20.66666667, 20.83333333, 21.        , 20.83333333, 21.        ,
       21.        , 21.16666667, 20.66666667, 21.        , 20.83333333,
       21.16666667, 20.66666667, 20.16666667, 20.33333333, 21.        ,
       21.        , 21.16666667, 21.        , 20.66666667, 20.83333333,
       20.83333333, 20.83333333, 21.16666667, 20.66666667, 20.83333333,
       20.66666667, 20.        , 20.        , 21.        , 20.83333333,
       21.        , 20.83333333, 20.5       , 20.83333333, 20.66666667,
       20.        , 21.33333333, 20.        , 21.        , 20.5       ,
       20.83333333, 21.        , 21.16666667, 20.66666667, 20.83333333,
       20.16666667, 20.66666667, 21.16666667, 20.83333333, 21.16666667,
       20.33333333, 21.        , 20.66666667, 21.        , 21.16

In [49]:
from sklearn.metrics import mean_squared_error as mse

In [50]:
mse(yunet_train, loaded_model.predict(Xunet_train))

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  30 out of  30 | elapsed:    0.0s finished


0.6264090177133659

In [51]:
mse(yunet_test, loaded_model.predict(Xunet_test))

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  30 out of  30 | elapsed:    0.0s finished


0.6761904761904765

In [52]:
loaded_model.predict(Xunet_test)

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  30 out of  30 | elapsed:    0.0s finished


array([20.5       , 20.66666667, 21.        , 20.66666667, 21.        ,
       20.66666667, 20.83333333, 20.16666667, 21.16666667, 20.66666667,
       20.83333333, 20.66666667, 21.33333333, 21.        , 21.        ,
       20.66666667, 20.66666667, 20.83333333, 20.83333333, 21.        ,
       20.66666667, 20.66666667, 21.16666667, 20.5       , 20.66666667,
       20.66666667, 20.83333333, 20.83333333, 21.        , 20.16666667,
       21.        , 20.83333333, 21.16666667, 20.5       , 20.5       ])

In [53]:
loaded_model.n_estimators

30

In [ ]:
loadeda_model.max_de