In [1]:
import numpy as np
from sklearn.externals import joblib
from sklearn.ensemble import RandomForestRegressor
import os
from sklearn.metrics import mean_squared_error, mean_absolute_error
import matplotlib.pyplot as plt

In [2]:
data_dir = '/storage/yw18581/data/'
data_folder = os.path.join(data_dir, 'train_validation_test')

In [3]:
def cut_X(arr, reshape = None):
    x_cut = arr[:,960:1300,600:]
    if reshape:
        if len(x_cut.shape)>3:
            x_cut = x_cut[...,0]
            x_cut_out = x_cut.reshape(x_cut.shape[0],x_cut.shape[1]*x_cut.shape[2])
    else:
        x_cut_out = x_cut
    return x_cut_out

def reshape_RF(arr):
    arr_RF = arr.reshape((arr.shape[0], arr.shape[1]*arr.shape[2]))
    return arr_RF

In [4]:
X_test = np.load(os.path.join(data_folder, 'Xy_test_dist.npz'))["y"]
y_test = np.load(os.path.join(data_folder, 'Xy_test_dist.npz'))["dist"]

In [6]:
unet_dir = os.path.join(data_dir, "trained_models",
                        "UNet_training_generator_1500epochs")

In [7]:
X_test_Unet = np.load(os.path.join(unet_dir, 'Xy_test_predicted_UNet.npz'))["y"]
y_test_Unet = np.load(os.path.join(unet_dir, 'Xy_test_predicted_UNet.npz'))["dist"]

In [18]:
X_1mm = np.load(os.path.join(data_folder, "Xy_1mm.npz"))["y"]
y_1mm = np.load(os.path.join(data_folder, "Xy_1mm.npz"))["dist"]

X_2mm = np.load(os.path.join(data_folder, "Xy_2mm.npz"))["y"]
y_2mm = np.load(os.path.join(data_folder, "Xy_2mm.npz"))["dist"]

X_3mm = np.load(os.path.join(data_folder, "Xy_3mm.npz"))["y"]
y_3mm = np.load(os.path.join(data_folder, "Xy_3mm.npz"))["dist"]

X_4mm = np.load(os.path.join(data_folder, "Xy_4mm.npz"))["y"]
y_4mm = np.load(os.path.join(data_folder, "Xy_4mm.npz"))["dist"]

X_10mm = np.load(os.path.join(data_folder, "Xy_10mm.npz"))["y"]
y_10mm = np.load(os.path.join(data_folder, "Xy_10mm.npz"))["dist"]

X_15mm = np.load(os.path.join(data_folder, "Xy_15mm.npz"))["y"]
y_15mm = np.load(os.path.join(data_folder, "Xy_15mm.npz"))["dist"]

X_20mm = np.load(os.path.join(data_folder, "Xy_20mm.npz"))["y"]
y_20mm = np.load(os.path.join(data_folder, "Xy_20mm.npz"))["dist"]

X_25mm = np.load(os.path.join(data_folder, "Xy_25mm.npz"))["y"]
y_25mm = np.load(os.path.join(data_folder, "Xy_25mm.npz"))["dist"]

X_30mm = np.load(os.path.join(data_folder, "Xy_30mm.npz"))["y"]
y_30mm = np.load(os.path.join(data_folder, "Xy_30mm.npz"))["dist"]

X_35mm = np.load(os.path.join(data_folder, "Xy_35mm.npz"))["y"]
y_35mm = np.load(os.path.join(data_folder, "Xy_35mm.npz"))["dist"]



In [7]:
X_1mm_Unet = np.load(os.path.join(unet_dir, "Xy_1mm_predicted_UNet.npz"))["y"]
y_1mm_Unet = np.load(os.path.join(unet_dir, "Xy_1mm_predicted_UNet.npz"))["dist"]

X_2mm_Unet = np.load(os.path.join(unet_dir, "Xy_2mm_predicted_UNet.npz"))["y"]
y_2mm_Unet = np.load(os.path.join(unet_dir, "Xy_2mm_predicted_UNet.npz"))["dist"]

X_3mm_Unet = np.load(os.path.join(unet_dir, "Xy_3mm_predicted_UNet.npz"))["y"]
y_3mm_Unet = np.load(os.path.join(unet_dir, "Xy_3mm_predicted_UNet.npz"))["dist"]

X_4mm_Unet = np.load(os.path.join(unet_dir, "Xy_4mm_predicted_UNet.npz"))["y"]
y_4mm_Unet = np.load(os.path.join(unet_dir, "Xy_4mm_predicted_UNet.npz"))["dist"]

X_10mm_Unet = np.load(os.path.join(unet_dir, "Xy_10mm_predicted_UNet.npz"))["y"]
y_10mm_Unet = np.load(os.path.join(unet_dir, "Xy_10mm_predicted_UNet.npz"))["dist"]

X_15mm_Unet = np.load(os.path.join(unet_dir, "Xy_15mm_predicted_UNet.npz"))["y"]
y_15mm_Unet = np.load(os.path.join(unet_dir, "Xy_15mm_predicted_UNet.npz"))["dist"]

X_20mm_Unet = np.load(os.path.join(unet_dir, "Xy_20mm_predicted_UNet.npz"))["y"]
y_20mm_Unet = np.load(os.path.join(unet_dir, "Xy_20mm_predicted_UNet.npz"))["dist"]

X_25mm_Unet = np.load(os.path.join(unet_dir, "Xy_25mm_predicted_UNet.npz"))["y"]
y_25mm_Unet = np.load(os.path.join(unet_dir, "Xy_25mm_predicted_UNet.npz"))["dist"]

X_30mm_Unet = np.load(os.path.join(unet_dir, "Xy_30mm_predicted_UNet.npz"))["y"]
y_30mm_Unet = np.load(os.path.join(unet_dir, "Xy_30mm_predicted_UNet.npz"))["dist"]

X_35mm_Unet = np.load(os.path.join(unet_dir, "Xy_35mm_predicted_UNet.npz"))["y"]
y_35mm_Unet = np.load(os.path.join(unet_dir, "Xy_35mm_predicted_UNet.npz"))["dist"]


In [ ]:
X_1mm_cut = cut_X(X_1mm)
X_1mm_RF = reshape_RF(X_1mm_cut)

X_2mm_cut = cut_X(X_2mm)
X_2mm_RF = reshape_RF(X_2mm_cut)

X_3mm_cut = cut_X(X_3mm)
X_3mm_RF = reshape_RF(X_3mm_cut)

X_4mm_cut = cut_X(X_4mm)
X_4mm_RF = reshape_RF(X_4mm_cut)

X_10mm_cut = cut_X(X_10mm)
X_10mm_RF = reshape_RF(X_10mm_cut)

X_15mm_cut = cut_X(X_15mm)
X_15mm_RF = reshape_RF(X_15mm_cut)

X_20mm_cut = cut_X(X_20mm)
X_20mm_RF = reshape_RF(X_20mm_cut)

X_25mm_cut = cut_X(X_25mm)
X_25mm_RF = reshape_RF(X_25mm_cut)

X_30mm_cut = cut_X(X_30mm)
X_30mm_RF = reshape_RF(X_30mm_cut)

X_35mm_cut = cut_X(X_35mm)
X_35mm_RF = reshape_RF(X_35mm_cut)


In [9]:
X_1mm_Unet_cut = cut_X(X_1mm_Unet)
X_1mm_Unet_RF = reshape_RF(X_1mm_Unet_cut)

X_2mm_Unet_cut = cut_X(X_2mm_Unet)
X_2mm_Unet_RF = reshape_RF(X_2mm_Unet_cut)

X_3mm_Unet_cut = cut_X(X_3mm_Unet)
X_3mm_Unet_RF = reshape_RF(X_3mm_Unet_cut)

X_4mm_Unet_cut = cut_X(X_4mm_Unet)
X_4mm_Unet_RF = reshape_RF(X_4mm_Unet_cut)

X_10mm_Unet_cut = cut_X(X_10mm_Unet)
X_10mm_Unet_RF = reshape_RF(X_10mm_Unet_cut)

X_15mm_Unet_cut = cut_X(X_15mm_Unet)
X_15mm_Unet_RF = reshape_RF(X_15mm_Unet_cut)

X_20mm_Unet_cut = cut_X(X_20mm_Unet)
X_20mm_Unet_RF = reshape_RF(X_20mm_Unet_cut)

X_25mm_Unet_cut = cut_X(X_25mm_Unet)
X_25mm_Unet_RF = reshape_RF(X_25mm_Unet_cut)

X_30mm_Unet_cut = cut_X(X_30mm_Unet)
X_30mm_Unet_RF = reshape_RF(X_30mm_Unet_cut)

X_35mm_Unet_cut = cut_X(X_35mm_Unet)
X_35mm_Unet_RF = reshape_RF(X_35mm_Unet_cut)



In [8]:
X_test_cut = cut_X(X_test)
X_test_RF = reshape_RF(X_test_cut)

In [9]:
X_test_Unet_cut = cut_X(X_test_Unet)
X_test_Unet_RF = reshape_RF(X_test_Unet_cut)

In [15]:
X_test_Unet_RF = X_test_Unet_RF.astype(np.uint8)*255

In [10]:
rf = joblib.load(os.path.join(data_dir,"trained_models","Leaf_position_regression","leaf_regression_RF_30est_8depth.pkl"))

### predict on test data

In [11]:
preds_test = rf.predict(X_test_RF)
mean_squared_error(y_test, preds_test)

0.05616203703703703

In [16]:
preds_test_Unet = rf.predict(X_test_Unet_RF)
mean_squared_error(y_test_Unet, preds_test_Unet)

0.04672685185185186

### Predict on unseen positions

In [11]:
preds_1mm = rf.predict(X_1mm_RF)

In [12]:
preds_1mm

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2.

In [13]:
preds_3mm = rf.predict(X_3mm_RF)

In [14]:
preds_3mm

array([2.26666667, 3.66666667, 3.6       , 3.73333333, 2.46666667,
       3.46666667, 3.86666667, 3.73333333, 3.8       , 3.26666667,
       3.33333333, 3.93333333, 3.8       , 3.93333333, 2.93333333,
       3.33333333, 3.93333333, 3.4       , 3.93333333, 2.93333333,
       3.53333333, 4.        , 3.73333333, 3.66666667, 2.46666667,
       3.26666667, 3.06666667, 3.73333333, 3.93333333, 3.26666667,
       3.73333333, 3.66666667, 3.46666667, 4.        , 2.4       ,
       3.8       , 3.4       , 3.73333333, 3.93333333, 2.26666667,
       2.8       , 3.93333333, 3.26666667, 2.46666667, 3.06666667,
       3.73333333, 4.        , 4.        , 3.73333333, 3.06666667,
       3.13333333, 3.93333333, 4.        , 2.4       , 2.93333333,
       3.93333333, 3.53333333, 3.33333333, 3.46666667, 2.13333333,
       3.53333333, 3.26666667, 3.26666667, 2.33333333, 3.4       ,
       3.8       , 3.93333333, 2.33333333, 3.46666667, 2.06666667,
       3.6       , 3.93333333, 3.66666667, 2.4       , 3.26666

In [15]:
preds_15mm = rf.predict(X_15mm_RF)

In [16]:
preds_15mm

array([14.5       , 15.        , 15.        , 15.        , 15.5       ,
       14.5       , 15.        , 15.        , 15.        , 16.        ,
       15.        , 15.        , 15.        , 14.5       , 15.        ,
       14.        , 15.        , 15.5       , 15.        , 14.5       ,
       15.        , 15.        , 15.        , 15.        , 15.        ,
       14.5       , 14.5       , 15.        , 15.        , 14.5       ,
       14.5       , 14.        , 15.        , 14.5       , 15.        ,
       15.        , 15.        , 15.        , 15.        , 14.        ,
       15.        , 15.        , 15.        , 15.        , 15.5       ,
       14.5       , 15.        , 15.        , 15.5       , 15.        ,
       15.        , 15.        , 15.        , 15.5       , 14.5       ,
       14.5       , 13.73333333, 15.        , 15.        , 14.8       ,
       14.5       , 15.        , 15.        , 15.        , 14.3       ,
       15.        , 15.        , 15.        , 15.        , 15.  

In [17]:
preds_20mm = rf.predict(X_20mm_RF)

In [18]:
preds_20mm

array([18.5, 18.5, 19. , 21. , 20.5, 20. , 19. , 19.5, 18. , 18.5, 20. ,
       21. , 20. , 21. , 19. , 19. , 20.5, 20. , 19. , 18.3, 20.5, 21.5,
       21.5, 19. , 18. , 18. , 19.5, 20.5, 21. , 18.5, 19. , 19.5, 21.5,
       19. , 20. , 19.5, 22. , 21. , 19.8, 18.5, 21. , 19. , 19.5, 20. ,
       19. , 18.5, 21.5, 20.5, 19.1, 18.5, 22. , 19. , 20. , 19.5, 18.5,
       19.5, 20. , 19.5, 19. , 18.5, 19.5, 20.5, 20.5, 19. , 18.5, 20. ,
       21. , 19. , 21. , 18.5, 19.5, 21. , 21.5, 18.5, 19. , 21.5, 19.5,
       20. , 21. , 18.5, 19.5, 21. , 19. , 18.5, 19. , 20.5, 19. , 18.5,
       21. , 19. , 18.5, 20.6, 20.5, 19.3, 19. , 20. , 19.5, 19. , 19.5,
       19. , 19.5, 20. , 20.6, 18. , 19. , 19.5, 20. , 19. , 18.5, 19.5,
       20. , 19.5, 19.5, 21. , 20. , 18. , 21.5, 20. , 18.5, 17.5, 19.5,
       20. , 20.5, 20. , 20. , 19. , 19. , 21. , 20. , 19. , 21.5, 20. ,
       19.5, 21.5, 18.5, 18.5, 22. , 22. , 19. , 19. , 19.5, 21. , 19. ,
       18.8, 19.3, 19.5, 21.5, 19.5, 21.5, 19. , 18

In [19]:
preds_30mm = rf.predict(X_30mm_RF)

In [20]:
preds_30mm

array([25. , 25. , 25. , 23.5, 25. , 25. , 23.5, 25. , 25. , 24.5, 25. ,
       25. , 24.5, 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 24.5,
       25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. ,
       25. , 25. , 25. , 24.5, 25. , 24.5, 24.5, 24. , 24.5, 25. , 25. ,
       25. , 25. , 25. , 25. , 24. , 25. , 25. , 25. , 25. , 25. , 25. ,
       25. , 25. , 24.5, 25. , 25. , 24.5, 25. , 25. , 24.5, 25. , 25. ,
       25. , 24. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. ,
       25. , 25. , 25. , 25. , 23.3, 25. , 25. , 24. , 25. , 25. , 25. ,
       25. , 25. , 24.5, 25. , 25. , 25. , 25. , 25. , 25. , 24.5, 25. ,
       25. , 25. , 25. , 25. , 25. , 24.5, 25. , 25. , 25. , 25. , 25. ,
       25. , 25. , 25. , 25. , 25. , 25. , 24. , 25. , 25. , 25. , 25. ,
       25. , 25. , 25. , 22. , 25. , 23.5, 25. , 25. , 25. , 24.5, 25. ,
       25. , 25. , 25. , 25. , 24.5, 25. , 25. , 25. , 25. , 25. , 25. ,
       25. , 25. , 25. , 25. , 25. , 23.5, 25. , 25

In [21]:
preds_35mm = rf.predict(X_35mm_RF)
preds_35mm

array([25. , 25. , 25. , 24.5, 25. , 25. , 25. , 25. , 25. , 25. , 25. ,
       25. , 25. , 25. , 25. , 24.5, 25. , 25. , 25. , 25. , 25. , 25. ,
       25. , 25. , 25. , 25. , 25. , 24. , 25. , 25. , 25. , 25. , 25. ,
       24. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. ,
       25. , 25. , 25. , 24.5, 25. , 25. , 25. , 25. , 25. , 25. , 25. ,
       25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. ,
       25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 24.5,
       25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. ,
       25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 24.5, 25. , 25. ,
       25. , 23. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. ,
       25. , 24.5, 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. ,
       25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. ,
       24. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. , 25. ,
       24. , 25. , 25. , 23. , 25. , 25. , 25. , 25

### Predict on unseen positions - UNet masks

In [22]:
preds_3mm_Unet = rf.predict(X_3mm_Unet_RF)
preds_15mm_Unet = rf.predict(X_15mm_Unet_RF)
preds_20mm_Unet = rf.predict(X_20mm_Unet_RF)

In [23]:
preds_3mm_Unet

array([4.        , 4.        , 4.        , 4.        , 4.        ,
       4.        , 4.        , 4.        , 4.        , 4.        ,
       4.        , 4.        , 3.93333333, 4.        , 4.        ,
       4.        , 4.        , 4.        , 4.        , 4.        ,
       4.        , 4.        , 4.        , 4.        , 4.        ,
       4.        , 4.        , 4.        , 4.        , 4.        ,
       4.        , 4.        , 4.        , 4.        , 4.        ,
       4.        , 4.        , 4.        , 4.        , 4.        ,
       3.93333333, 4.        , 4.        , 4.        , 4.        ,
       4.        , 4.        , 4.        , 4.        , 4.        ,
       4.        , 4.        , 4.        , 4.        , 4.        ,
       4.        , 4.        , 4.        , 4.        , 4.        ,
       4.        , 4.        , 4.        , 4.        , 4.        ,
       4.        , 3.93333333, 4.        , 4.        , 4.        ,
       4.        , 4.        , 4.        , 4.        , 4.     

In [24]:
preds_15mm_Unet

array([15. , 15.5, 15.5, 16. , 16. , 16.5, 16. , 16.5, 15.5, 17. , 16.5,
       17. , 17. , 15.5, 15.5, 16.5, 15. , 15.5, 16. , 17. , 15.5, 15.5,
       16. , 16. , 16.5, 17. , 15.5, 15. , 16.5, 16.5, 16.5, 16.5, 15. ,
       16. , 15.5, 15.5, 16. , 15. , 16. , 17. , 16.5, 16.5, 16. , 15.5,
       17. , 17. , 16. , 16.5, 16. , 17. , 16.5, 17. , 16.5, 16. , 17. ,
       15.5, 16. , 15. , 16. , 16. , 17. , 15.5, 16. , 16. , 16.5, 16. ,
       16. , 15.5, 17. , 17. , 16.5, 16.5, 15. , 15. , 16.5, 16. , 17. ,
       16. , 15.5, 15.5, 16. , 17. , 16. , 16. , 17. , 16.5, 17. , 17. ,
       16.5, 16. , 16.5, 17. , 17. , 16. , 16.5, 16.5, 15.5, 15.5, 16.5,
       15.5, 15.5, 16. , 15. , 16. , 15.5, 16.5, 16.5, 16. , 15.5, 17. ,
       16. , 16.5, 15.5, 17. , 16. , 16.5, 17. , 16. , 15. , 16.5, 17. ,
       15.5, 15. , 16. , 17. , 16.5, 17. , 16. , 16. , 16.5, 16. , 16. ,
       16.5, 16.5, 16.5, 17. , 16. , 16.5, 15. , 16.5, 16. , 16. , 17. ,
       16. , 16. , 17. , 15. , 17. , 16. , 17. , 17

In [25]:
preds_20mm_Unet

array([23.5, 22. , 22.5, 22. , 22.5, 22. , 23.5, 22.5, 23. , 22. , 21.5,
       22. , 23. , 22.5, 23.5, 23. , 23. , 22.5, 23. , 23. , 23.5, 22.5,
       22. , 23. , 22.5, 22.5, 23. , 22.5, 22.5, 22. , 23. , 23. , 23.5,
       22.5, 22.5, 23.5, 23. , 22.5, 22.5, 22. , 23. , 23. , 22.5, 22.5,
       22.5, 23. , 23. , 22.5, 22.5, 22.5, 22. , 23. , 23. , 23. , 23. ,
       22. , 22.5, 23. , 23. , 22.5, 22. , 23. , 23.5, 22.5, 23. , 23. ,
       21. , 23.5, 23. , 23. , 22.5, 22.5, 22.5, 23. , 23. , 22.5, 22.5,
       23. , 23. , 22.5, 22.5, 22. , 23.5, 22.5, 22.5, 23. , 22.5, 23. ,
       22.5, 22. , 22.5, 23.5, 23. , 23. , 22. , 22.5, 22.5, 23. , 22. ,
       22. , 22.5, 22.5, 22.5, 23. , 22. , 23. , 22. , 23.5, 22. , 23. ,
       22.5, 22. , 23.5, 22.5, 23. , 22. , 23. , 22. , 23. , 22. , 22. ,
       23. , 23. , 22.5, 23. , 23. , 22.5, 22. , 22.5, 23. , 22. , 22.5,
       23. , 23. , 23. , 22.5, 23. , 21. , 23.5, 22.5, 22.5, 23. , 22. ,
       23. , 24. , 23. , 21.5, 22. , 23.5, 23. , 23

### retrain rf on all data

In [ ]:
X = np.vstack((X_1mm_RF, X_2mm_RF,X_3mm_ X_4mm_RF))

In [ ]:
y = np.hstack((y_1mm, y_2mm, y_4mm))